"""Add AI analysis summary and confidence

Revision ID: d60d18122ebc
Revises: 87db6a21b127
Create Date: 2026-09-11 01:01:50.687685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd60d18122ebc'
down_revision: Union[str, Sequence[str], None] = '87db6a21b127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge_ai_analysis', sa.Column('problem_summary', sa.Text(), nullable=True))
    op.add_column('challenge_ai_analysis', sa.Column('confidence_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenge_ai_analysis', 'confidence_score')
    op.drop_column('challenge_ai_analysis', 'problem_summary')
    # ### end Alembic commands ###
